version: '3.8'

services:
  api:
    image: olivervea/veachron-api:latest
    build:
      context: .
      dockerfile: Api.Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      LOG_LEVEL: WARNING

  ui:
    image: olivervea/veachron-ui:latest
    build:
      context: .
      dockerfile: Ui.Dockerfile

  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: veachron
    volumes:
    - postgresql:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
    - pgadmin:/var/lib/pgadmin

  nginx:
    image: nginx:1.21
    platform: linux
    ports:
      - 80:80
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgresql:
  pgadmin:
