version: '3.8'

services:
  api:
    build:
      context: ./
    ports:
      - 80:5000
    volumes:
      - ./:/usr/src/app

  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: veachron
    volumes:
    - postgresql:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
    - 5050:80
    volumes:
    - pgadmin:/var/lib/pgadmin

volumes:
  postgresql:
  pgadmin:
