version: '3.8'

services:
  api:
    build:
      context: ./
    ports:
      - 80:5000
    volumes:
      - ./:/usr/src/app
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password

  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: veachron
    volumes:
    - postgresql:/var/lib/postgresql/data
    ports:
    - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
    - 5050:80
    volumes:
    - pgadmin:/var/lib/pgadmin

volumes:
  postgresql:
  pgadmin:
