name: Publish Docker image
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: API Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Api.Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/veachron-api:latest

    - name: UI Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Ui.Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/veachron-ui:latest
